### PR TITLE
NXP-29504: adapt usage of runtime messages api

### PR DESCRIPTION
**Pull request by atchertchian**
Depends on https://github.com/nuxeo/nuxeo/pull/4249

### CODE REVIEW

**Comment by atchertchian** [comment]
After 11.2 release, it seems that jsf-ui is not aligned on 11.3-SNAPSHOT but on 11.2 (fixed dependency), so i presume this PR should be closed instead: please confirm.

Update: align on 11.3-SNAPSHOT done in the meantime

**Review by efge — DISMISSED** [review]

**Comment by atchertchian** [comment]
Will need https://github.com/nuxeo/nuxeo/pull/4249 to be merged and successfully deployed before corresponding validation checks can be done.

**Review by kevinleturc — DISMISSED** [review]

**Review by efge — DISMISSED** [review]

**Comment by atchertchian** [comment]
Waiting for a nuxeo master valid deployment

**Comment by atchertchian** [comment]
Force pushed as branch was still aligned on nuxeo 11.2...

**Pull request merged**
