### PR TITLE
NXP-28915: display bundle and component requirements in JSF UI

### PR DESCRIPTION
**Pull request by atchertchian**

### CODE REVIEW

**Comment by atchertchian** [comment]
Depends on https://github.com/nuxeo/nuxeo/pull/3961 and https://github.com/nuxeo/nuxeo/pull/3959

T&P ongoing: https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-master/206

**Comment by atchertchian** [comment]
T&P https://qa.nuxeo.org/jenkins/job/TestAndPush/job/ondemand-testandpush-atchertchian-master/207 failed on JSF this time --> need to properly rebase this branch on top of  feature-NXP-28913-explorer-small-improvements (see #54)

**Comment by atchertchian** [comment]
T&P finally went through (see #57)

**Review by efge — DISMISSED** [review]

**Comment by atchertchian** [comment]
Rebased on master after merge of #54

**Review by efge — APPROVED** [review]

**Pull request merged**
