### PR TITLE
NXP-29984: adapt to ActionService API changes

### PR DESCRIPTION
**Pull request by atchertchian**
Depends on PR at https://github.com/nuxeo/nuxeo/pull/4575

### CODE REVIEW

**Review by efge — DISMISSED** [review]

**Review by kevinleturc — DISMISSED** [review]

**Comment by atchertchian** [comment]
(force pushed to rebase, otherwise validations fail on missing dependencies that have been upgraded in the meantime)

**Comment by atchertchian** [comment]
Updated action-related unit tests (as the equals method checking only the id attribute was removed)

**Comment by atchertchian** [comment]
Tests actually reveal an issue with default merge of filters -> will revert that behaviour change on nuxeo side.

**Comment by atchertchian** [comment]
Merging as is to fix the master build (will revert the change on unit test once change behaviour about implicit merge on filters is reverted on nuxeo side).

**Pull request merged**
