### PR TITLE
NXP-30110: Make the build grep for errors in all functional tests (an…

### PR DESCRIPTION
**Pull request by atchertchian**
…d archive html files)

### CODE REVIEW

**Review by troger — DISMISSED** [review]

**Comment by atchertchian** [comment]
Needs fix from https://github.com/nuxeo/nuxeo/pull/4639 to go through.
Also changed the order of tests to make most important tests go through first: I thought I broke JSF theme in hot reload use case while it was broken in all cases, so moved "regular" tests up in the list.

**Comment by atchertchian** [comment]
TODO: maybe adapt test result to make it unstable (see https://github.com/nuxeo/nuxeo/pull/4641)

**Comment by kevinleturc** [comment]
> TODO: maybe adapt test result to make it unstable (see [nuxeo/nuxeo#4641](https://github.com/nuxeo/nuxeo/pull/4641))

Agree

**Comment by atchertchian** [comment]
Validation shows error logs.... on the platform-error ftests logs :sweat_smile: -> will exclude this one

**Comment by atchertchian** [comment]
Will be handled with https://jira.nuxeo.com/browse/NXP-30155 after all -> close

**Pull request closed without merging**
